# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZtt2u1qxWhvWUaQ-iUHmtjYhdv1hs0u

calculadora
"""

print("CALCULADORA SIMPLES")
print("1. Soma")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")


opcao = int(input("Escolha uma opção (1-4): "))


num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))


if opcao == 1:
    resultado = num1+num2
    print("A Soma de",num1,"e",num2," é:",resultado)
elif opcao == 2:
    resultado = num1-num2
    print("A Subtração de",num1,"e",num2,"  é:",resultado)
elif opcao == 3:
    resultado = num1*num2
    print("A Multiplicação de",num1,"e",num2,"  é:",resultado)
elif opcao == 4:
    resultado = num1/num2
    print("A Divisão de",num1,"e",num2,"  é:",resultado)
else:
    print("Opção inválida. Por favor, escolha uma opção válida.")